# jbloxDB
# © 2025 Green Arrowhead LLP
# Licensed under the jbloxDB License v1.0
# See LICENSE.txt for terms.
# Free for individuals and small companies.
# Commercial license required for production use by companies over USD 5M revenue or for SaaS/product distribution.


#initial file size (in MBs), file size of data file (used to store data)
#that you expect not to out grow soon. You will have to restart
#jbloxDB if file size is reached. jbloxDB might restart on its own
#if jbloxDB is not started by the admin.
initfilesize = "800;issues:1;comment:1;session:1;usersalary_large_forTest:2000" 

#once file size reaches initfilesize, jbloxDB increases size by this
#multiple, for the first time and thereafter everytime it reaches the
#new max size
newfilesizemultiplier = 2 

#directory containing data files
datadir = "./data"

#directory for log file
logdir = "./log"

#max number of records in get
maxgetrecords = 100

#maximum length of record
maxrecordlength = 40960

#max number of lines in log file before creating a new one
#'0' indicates do not recreate ever.
logmaxlines = 5000
 
#delimiter used to separate name and value of index
indexnamevaluedelimiter = "-"

#delimiter used to separate multiple keys
indexdelimiter = "`"

#delimeter used to separate timestamp;keys;records in the database files
recorddelimiter = ":"

#replacemenet for indexnamevaluedelimiter, if record contain delimter
#used by jbloxdb, they will be replace by the following
repindexnamevaluedelimiter = "_"

#replacemenet for indexdelimiter, if record contain delimter
#used by jbloxdb, they will be replace by the following
repindexdelimiter = "_"

#replacemenet for recorddelimiter, if record contain delimter
#used by jbloxdb, they will be replace by the following
reprecorddelimiter = "_"

#feature enables to view deleted records if they exist in the file
enableviewdelete = true

#max length of string to print on console for log
maxlogtoconsolelength = 100

#For Future Versions, not used currently
#configuration for mmap : OS intructions (only in unix/linux based OS)
#windows does it automatically
#
#in GB
MADVISE_CHUNK = 4
#enable only when following flag is true
low_ram_mode = false

notoperator = "!"

#sanity check time goback time in seconds
sanitycheckgobacksec = 0

#debugmode
debugmode = false

#if following mode is enabled, any OS error encountered
#while writing the data to disc will be logged in jblox_error-<timestamp>.log
#OS error encountered are rare, but they might occur. So, set this variable to 
#true if data loss is not acceptable even in rare cases. If data loss is acceptable, for e.g.
#in case of time series data, in rare cases, set following to false.
#Setting this variable to true could slow down the insert operations by a factor of upto 5X
strongdurablemode = false