name: Build and Package for Linux (Static)

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install musl-tools
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Add musl target
      run: rustup target add x86_64-unknown-linux-musl

    - name: Build Static Binary
      run: cargo build --release --target x86_64-unknown-linux-musl

    - name: Package Binary
      run: |
        mkdir -p dist/
        cp target/x86_64-unknown-linux-musl/release/jbloxdb dist/
        cp -r config dist/
        cp -r html dist/
        cp -r data dist/
        cp -r log dist/        
        tar -czvf jbloxdb-linux-static.tar.gz -C dist .

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jbloxdb-linux-static
        path: jbloxdb-linux-static.tar.gz
