name: Build and Package for Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Build Release Binary
      run: cargo build --release

    - name: Create .tar.gz Package
      run: |
        mkdir -p dist/
        cp target/release/jbloxDB dist/
        tar -czvf yourapp-linux.tar.gz -C dist jbloxDB

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: yourapp-linux
        path: yourapp-linux.tar.gz
